baseURL = "https://foamscience.github.io/amr-lb/"
languageCode = "en-us"
title = "Load-Balanced adaptive mesh refinement"

theme = "reveal-hugo"


[markup.goldmark.renderer]
unsafe = true
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
highlight_theme = "a11y-light"
custom_css = "css/customized.css"
width = "1200"
